# Generated by Django 4.0.4 on 2022-04-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name': 'Mi Departamento', 'verbose_name_plural': 'Areas de mi Empresa'},
        ),
    ]
