# Generated by Django 4.0.4 on 2022-04-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades Empleados',
            },
        ),
        migrations.AlterModelOptions(
            name='personas',
            options={'ordering': ['first_lastname'], 'verbose_name': 'Empleados', 'verbose_name_plural': 'Empleado'},
        ),
        migrations.AddField(
            model_name='personas',
            name='habilidad',
            field=models.ManyToManyField(to='persona.habilidades'),
        ),
    ]
