# Generated by Django 4.0.4 on 2022-04-30 16:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_habilidades_alter_personas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
    ]
