# Generated by Django 4.0.4 on 2022-05-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_personas_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombres Completos'),
        ),
    ]
