# Generated by Django 4.0.4 on 2022-05-17 00:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_options'),
        ('persona', '0004_personas_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='departamento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='habilidad',
            field=models.ManyToManyField(blank=True, to='persona.habilidades'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='job',
            field=models.CharField(blank=True, choices=[('0', 'Contador'), ('1', 'Adminitrador'), ('2', 'Economista'), ('3', 'Otro')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
